name: cdrift-evaluation
channels:
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pip
  - pip:
    - pm4py==2.2.17.1
    - wasserstein==1.0.1
    - strsimpy==0.2.1
    - ruptures==1.1.5
    - hotelling==0.5.0
    - pulp==2.6.0
    - scikit-learn==1.1.2
    - plotly==5.9.0
    - kaleido==0.0.3
    - nbformat==5.5.0
    - seaborn==0.12.0
    - ipykernel==6.22.0